version: '3.8'

services:
  devconnect:
    build: .
    container_name: devconnect-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devconnect
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
    networks:
      - dev-connect
  postgres:
    image: postgres:16
    container_name: devconnect-postgres
    environment:
      POSTGRES_DB: devconnect
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-connect

volumes:
  postgres-data:

networks:
  dev-connect:
    external: true