spring:
  application:
    name: devconnect
server:
  port: 8080
jwt:
  secret: sua_chave_super_secreta_de_32+_caracteres
app:
  kafka:
    batch_size: 16384
    buffer_size: 33554432
    ack: all
    topics:
      - name: dev-profile.created.v1
        partitions: 3
        replicas: 1
        retention-ms: 604800000
        cleanup-policy: delete
        create-dlt: true