name: Validate PR Size

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  check-pr-size:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR changes
        uses: actions-ecosystem/action-get-diff@v1
        id: diff
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '**/*'

      - name: Get PR diff stats
        id: pr-stats
        run: |
          added=$(echo "${{ steps.diff.outputs.added_files }}" | wc -l)
          modified=$(echo "${{ steps.diff.outputs.modified_files }}" | wc -l)
          removed=$(echo "${{ steps.diff.outputs.removed_files }}" | wc -l)
          total=$((added + modified + removed))
          echo "total_changes=$total" >> $GITHUB_OUTPUT

      - name: Fail if PR is too large
        if: steps.pr-stats.outputs.total_changes > 500
        run: |
          echo "❌ PR muito grande! (${ {steps.pr-stats.outputs.total_changes} } mudanças)"
          echo "Considere dividir em PRs menores."
          exit 1
